import { contextBridge, ipcRenderer } from 'electron';
import type { GitPadApi } from '../src/shared/api.js';

const invoke = <T>(channel: string, ...args: unknown[]) => ipcRenderer.invoke(channel, ...args) as Promise<T>;

const api: GitPadApi = {
  getSettings: () => invoke('settings:get'),
  updateSettings: (settings) => invoke('settings:update', settings),
  listWorkspaces: () => invoke('workspace:list'),
  createWorkspace: (input) => invoke('workspace:create', input),
  openWorkspace: (path) => invoke('workspace:open', path),
  renameWorkspace: (input) => invoke('workspace:rename', input),
  deleteWorkspace: (input) => invoke('workspace:delete', input),
  getFileTree: (workspacePath) => invoke('fs:tree', workspacePath),
  readFile: (workspacePath, relativePath) => invoke('fs:read', workspacePath, relativePath),
  saveFile: (input) => invoke('fs:save', input),
  createFile: (workspacePath, relativePath, content) => invoke('fs:create-file', workspacePath, relativePath, content),
  createDirectory: (workspacePath, relativePath) => invoke('fs:create-directory', workspacePath, relativePath),
  renamePath: (input) => invoke('fs:rename', input),
  duplicatePath: (input) => invoke('fs:duplicate', input),
  deletePath: (workspacePath, relativePath) => invoke('fs:delete', workspacePath, relativePath),
  search: (workspacePath, query) => invoke('search:query', workspacePath, query),
  advancedSearch: (input) => invoke('search:advanced', input),
  getNoteGraph: (workspacePath) => invoke('notes:graph', workspacePath),
  getBacklinks: (workspacePath, relativePath) => invoke('notes:backlinks', workspacePath, relativePath),
  ensureLinkedNote: (workspacePath, noteName) => invoke('notes:ensure-linked', workspacePath, noteName),
  quickCapture: (workspacePath, content) => invoke('notes:quick-capture', workspacePath, content),
  executeCodeSnippet: (workspacePath, language, code, sourcePath, blockKey) =>
    invoke('execution:run-snippet', workspacePath, language, code, sourcePath, blockKey),
  executeCodeFile: (workspacePath, relativePath) => invoke('execution:run-file', workspacePath, relativePath),
  gitStatus: (workspacePath) => invoke('git:status', workspacePath),
  gitBranches: (workspacePath) => invoke('git:branches', workspacePath),
  gitCreateBranch: (workspacePath, name) => invoke('git:branch-create', workspacePath, name),
  gitSwitchBranch: (workspacePath, name) => invoke('git:branch-switch', workspacePath, name),
  gitRenameBranch: (workspacePath, oldName, newName) => invoke('git:branch-rename', workspacePath, oldName, newName),
  gitDeleteBranch: (workspacePath, name) => invoke('git:branch-delete', workspacePath, name),
  gitStagingStatus: (workspacePath) => invoke('git:staging-status', workspacePath),
  gitStagePath: (workspacePath, relativePath) => invoke('git:stage-path', workspacePath, relativePath),
  gitUnstagePath: (workspacePath, relativePath) => invoke('git:unstage-path', workspacePath, relativePath),
  gitStageAll: (workspacePath) => invoke('git:stage-all', workspacePath),
  gitUnstageAll: (workspacePath) => invoke('git:unstage-all', workspacePath),
  gitDiscardPath: (workspacePath, relativePath) => invoke('git:discard-path', workspacePath, relativePath),
  gitDiscardAll: (workspacePath) => invoke('git:discard-all', workspacePath),
  gitCommitStaged: (workspacePath, message, author) => invoke('git:commit-staged', workspacePath, message, author),
  gitDiffPath: (workspacePath, relativePath, mode) => invoke('git:diff-path', workspacePath, relativePath, mode),
  gitMergeBranch: (workspacePath, sourceBranch) => invoke('git:merge-branch', workspacePath, sourceBranch),
  gitSyncStatus: (workspacePath) => invoke('git:sync-status', workspacePath),
  gitCommit: (workspacePath, message) => invoke('git:commit', workspacePath, message),
  gitHistory: (workspacePath) => invoke('git:history', workspacePath),
  gitCommitDetails: (workspacePath, hash) => invoke('git:details', workspacePath, hash),
  gitFileHistory: (workspacePath, relativePath) => invoke('git:file-history', workspacePath, relativePath),
  gitRestoreFile: (workspacePath, hash, relativePath) => invoke('git:restore-file', workspacePath, hash, relativePath),
  gitRevertCommit: (workspacePath, hash) => invoke('git:revert', workspacePath, hash),
  createSnapshot: (workspacePath, name) => invoke('git:snapshot-create', workspacePath, name),
  listSnapshots: (workspacePath) => invoke('git:snapshot-list', workspacePath),
  restoreSnapshot: (workspacePath, tag) => invoke('git:snapshot-restore', workspacePath, tag),
  analytics: (workspacePath) => invoke('analytics:get', workspacePath),
  terminalRun: (workspacePath, command) => invoke('terminal:run', workspacePath, command),
  githubSaveToken: (workspacePath, input) => invoke('github:save-token', workspacePath, input),
  githubPush: (workspacePath) => invoke('github:push', workspacePath),
  githubPull: (workspacePath) => invoke('github:pull', workspacePath),
  authRegister: (username, email, password) => invoke('auth:register', username, email, password),
  authLogin: (identifier, password) => invoke('auth:login', identifier, password),
  authLogout: () => invoke('auth:logout'),
  authSession: () => invoke('auth:session'),
  authUsers: () => invoke('auth:users'),
  activityFeed: (workspacePath) => invoke('activity:feed', workspacePath),
  activityRecord: (event) => invoke('activity:record', event)
};

contextBridge.exposeInMainWorld('gitpad', api);
